openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/szilipeti95/ImagyApi/1.0.0
info:
  description: API for Imagy App
  version: "1.0.1"
  title: Imagy API
tags:
  - name: authorized
    description: Logged in user api calls
  - name: unauthorized
    description: Guest user api calls
paths:
  /login:
    post:
      tags:
        - unathorized
      summary: user login
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: login result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponse'
        '401':
          description: username or password error
  /register:
    post:
      tags:
        - unathorized
      summary: user register
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: register result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponse'
        '401':
          description: username is already taken
  /album:
    get:
      tags:
        - unauthorized
      summary: returns the albums
      parameters:
        - in: query
          name: filter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: search result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'
    post:
      tags:
        - authorized
      summary: adds new album
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/NewAlbum'
      responses:
        '200':
          description: register result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponse'
  /album/delete/{albumId}:
    delete:
      tags:
        - authorized
      summary: deletes album
      parameters:
        - in: path
          name: albumId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: delete result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponse'

  /album/self:
    get:
      tags:
        - authorized
      summary: returns the albums of the requestor
      responses:
        '200':
          description: search result
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'
  /album/images/{albumId}:
    get:
      tags:
        - unauthorized
      summary: returns the images in a album
      parameters:
        - in: path
          name: albumId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: image uris in the album
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
  /album/like/{albumId}:
    post:
      tags:
        - authorized
      summary: likes album
      parameters:
        - in: path
          name: albumId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: image uris in the album
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RequestResponse'
  /album/unlike/{albumId}:
    post:
      tags:
        - authorized
      summary: unlikes album
      parameters:
        - in: path
          name: albumId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: image uris in the album
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RequestResponse'
  /user/self:
    get:
      tags:
        - authorized
      summary: returns the authenticated user
      responses:
        '200':
          description: user result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /image/{image-uri}:
    get:
      tags:
        - unauthorized
      summary: returns the image
      parameters:
        - in: path
          name: image-uri
          required: true
          schema:
            type: string
      responses:
        '200':
          description: search result
          content:
            image/png:
              schema:
                type: string
                format: binary
  /image:
    post:
      tags:
        - authorized
      summary: adds new image to album
      requestBody:
        content:
          image/png:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: register result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResponse'
components:
  schemas:
    AuthRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: test
        password:
          type: string
          example: password
    User:
      type: object
      required:
        - email
        - username
        - password
        - likedCount
        - profileImageUri
      properties:
        email:
          type: string
          example: 'email'
        username:
          type: string
          example: 'username'
        password:
          type: string
          example: 'password'
        likedCount:
          type: integer
          example: 10
        profileImageUri:
          type: string
          example: 'image-1'
    NewAlbum:
      type: object
      required:
        - name
        - tags
      properties:
        name:
          type: string
          example: 'album name'
        tags:
          type: array
          items:
            type: string
            example: ['tag1', 'tag2']
    Album:
      type: object
      required:
        - id
        - name
        - author
        - likeCount
        - tags
        - creationDate
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'album name'
        author:
          type: string
          example: 'user1'
        likeCount:
          type: integer
          example: 10
        tags:
          type: array
          items:
            type: string
            example: ['tag1', 'tag2']
        creationDate:
          type: integer
          example: 1573916863
    Image:
      type: object
      required:
        - imageUri
      properties:
        imageUri:
          type: string
          example: 'image-uri'
    RequestResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: 'Successfully uploaded'
